# This CI configuration file is used to Test the Funkwhale API wrapper every time there is a change in sources.
# In order to work, A Gitlab Runner with Windows Server 2016 Standard with the following packages is used:
# * Python 3.7.2.
# * Microsoft Visual C++ 2015 redistributable files

# Declare some variables dependent on the operating system where the runner is installed.
# This CI file assumes we install everything in C:\ (Python 2.7, 3.7 and Nsis).
variables:
  PYTHON: "C:\\python37\\python.exe"
  
stages:
    - test

test:
  stage: test
  tags:
    - windows10
  before_script:
    - '%PYTHON% -V'
    - '%PYTHON% -m pip install --upgrade pip'
    - '%PYTHON% -m pip install --upgrade -r requirements.txt'
  script:
    - '%PYTHON% -m coverage run run_tests.py'
    - '%PYTHON% -m coverage report --omit="test*"'
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  only:
    - master
    - tags
    - schedule_pipelines